#server:
#  port:  8402
#spring:
#  application:
#    name: config-client
#  cloud:
#    config:
#      profile: dev
##    profiles:
##        active: default
#
##配置仓库的分支
#      label: master
#
##      discovery:
###从配置中心读取文件
##        enabled: true
###配置中心的servieId，即服务名。
##        serviceId : config-server
#
#
##      uri: http://localhost:8401
##      enabled: true
#
#
##服务注册中心
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8101/eureka/
#
#
#
##配置服务中心的网址
##spring.cloud.bootstrap.enabled=false
#
