spring:
  application:
    name: service-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
#  instance:
#    prefer-ip-address: true
#    instanceId: ${spring.application.name}:${server.port}

#feign.hystrix.enabled=true
feign:
  hystrix:
    enabled: true
server:
  port: 8302

