#server.port=8764
#eureka.instance.hostname=localhost
#eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname}:8761/eureka/
#spring.application.name=micro-service-ribbon

spring:
  application:
    name: service-ribbon

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
server:
  port:  8301
